/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Setup;

import MasterClass.Catagary1Data;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author chamod
 */
public class CatagaryRegistration extends javax.swing.JInternalFrame {

    Catagary1Data Catagary1Data = new Catagary1Data();

    /**
     * Creates new form HospitalRegister
     */
    public CatagaryRegistration() {
        initComponents();
        ShowGrid();
        category_id.hide();
        category_delete_btn.hide();
         ShowGrid();
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"id", "Catagary Name"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                return false;
            }
        };

        tblGrid.setModel(model);
        tblGrid.getTableHeader().setPreferredSize(new Dimension(tblGrid.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = tblGrid.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        RequestViewTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer); */
        TableColumn colou10 = tblGrid.getColumnModel().getColumn(0);
        colou10.setMinWidth(0);
        colou10.setPreferredWidth(0);
        colou10.setMaxWidth(0);

//        TableColumn colou110 = tblGrid.getColumnModel().getColumn(1);
//        colou110.setMinWidth(90);
//        colou110.setPreferredWidth(90);
//        colou110.setMaxWidth(90);
        tblGrid.setModel(model);

        getData();

    }

    public void getData() {

        try {
            ResultSet set = null;
            String data[][] = null;
            DefaultTableModel dtf = (DefaultTableModel) tblGrid.getModel();
            dtf.setRowCount(0);
            set = Catagary1Data.GetCatagary1();
            set.last();
            data = new String[set.getRow()][2];
            set.beforeFirst();
            int x = 0;
            while (set.next()) {
                data[x][0] = set.getString("id");
                data[x][1] = set.getString("catagary_name");
                x++;
            }
            set.close();
            set = null;

            //String data[][] = null; 
            String colu[] = new String[]{"id", "Catagary Name"};
            DefaultTableModel model = new DefaultTableModel(data, colu) {
                //@Override
                public boolean isCellEditable(int x, int y) {
                    return false;
                }
            };

            tblGrid.setModel(model);
            tblGrid.getTableHeader().setPreferredSize(new Dimension(tblGrid.getTableHeader().getPreferredSize().width, 35));
            JTableHeader head = tblGrid.getTableHeader();
            head.setFont(head.getFont().deriveFont(Font.BOLD));

            TableColumn colou10 = tblGrid.getColumnModel().getColumn(0);
            colou10.setMinWidth(0);
            colou10.setPreferredWidth(0);
            colou10.setMaxWidth(0);

//            TableColumn colou110 = tblGrid.getColumnModel().getColumn(1);
//            colou110.setMinWidth(90);
//            colou110.setPreferredWidth(90);
//            colou110.setMaxWidth(90);
            tblGrid.setModel(model);

            data = null;
            colu = null;
        } catch (Exception ex) {
            ex.printStackTrace();
            //Logger.getLogger(MainAccountSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        category_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        category_save_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrid = new javax.swing.JTable();
        category_name = new javax.swing.JTextField();
        category_delete_btn = new javax.swing.JButton();
        new_btn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category registration");

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category_id.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jPanel1.add(category_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 10, 10));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Category 1 Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 30));

        category_save_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        category_save_btn.setText("Save");
        category_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(category_save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 100, 25));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel3.setText("Category Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 20));

        tblGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Category Name"
            }
        ));
        tblGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrid);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 560, 190));

        category_name.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jPanel1.add(category_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 310, 25));

        category_delete_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        category_delete_btn.setText("Delete");
        category_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(category_delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 100, 25));

        new_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        new_btn.setText("New");
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });
        jPanel1.add(new_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void category_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_save_btnActionPerformed
        if (category_save_btn.getText() == "Save") {
            int val = Catagary1Data.SaveCatagary1(category_name.getText());

            if (val > 0) {
                JOptionPane.showMessageDialog(null, " Save Succesfull ");
                newForm();
            } else {
                JOptionPane.showMessageDialog(null, " Save not complete ");
            }

        } else {
            int val = Catagary1Data.updateCatagary1(category_id.getText(), category_name.getText());

            if (val > 0) {
                JOptionPane.showMessageDialog(null, " Edit Succesfull ");
                newForm();
            } else {
                JOptionPane.showMessageDialog(null, " Edit not complete ");
            }
        }
    }//GEN-LAST:event_category_save_btnActionPerformed

    private void tblGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGridMouseClicked
        if (evt.getClickCount() == 2) {

            //every other clicks loads data to fields
            try {
                category_id.setText(tblGrid.getValueAt(tblGrid.getSelectedRow(), 0).toString());
                category_name.setText(tblGrid.getValueAt(tblGrid.getSelectedRow(), 1).toString());
                category_save_btn.setText("Edit");
//                category_delete_btn.show();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tblGridMouseClicked

    private void category_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_delete_btnActionPerformed
 int val = Catagary1Data.DeleteCatagary1(category_id.getText());

            if (val > 0) {
                JOptionPane.showMessageDialog(null, " Delete Succesfull ");
                newForm();
            } else {
                JOptionPane.showMessageDialog(null, " Delete not complete ");
            }
    }//GEN-LAST:event_category_delete_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
       newForm();
    }//GEN-LAST:event_new_btnActionPerformed

    public void newForm() {
        category_name.setText("");
        category_id.setText("");
        category_save_btn.setText("Save");
        category_delete_btn.hide();
        getData();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton category_delete_btn;
    private javax.swing.JTextField category_id;
    private javax.swing.JTextField category_name;
    private javax.swing.JButton category_save_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton new_btn;
    private javax.swing.JTable tblGrid;
    // End of variables declaration//GEN-END:variables
}
