/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Setup;

import MasterClass.BlockData;
import MasterClass.BranchData;
import MasterClass.CustomerData;
import MasterClass.CustomerMobileData;
import MasterClass.LocationData;
import popups.CustomerDataUpdate;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author chamod
 */
public class CustomerMobileDataSearch extends javax.swing.JInternalFrame {

    CustomerData customerData = new CustomerData();
    BranchData branchData = new BranchData();
    BlockData blockData = new BlockData();
    LocationData locationData = new LocationData();
    CustomerMobileData customerMobileData = new CustomerMobileData();

    /**
     * Creates new form Branch
     */
    public CustomerMobileDataSearch() {
        initComponents();
        load_branch();
        load_location();
        ShowGrid();
    }

    private void load_branch() {
        try {
            ResultSet set = branchData.getBranch();
            set.last();
            set.beforeFirst();
            while (set.next()) {
                String branch_name = set.getString("branch_name");
                branch_select.addItem(branch_name);
            }
            set.close();
            set = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Branch Loading not complete ");
        }
    }

    private void load_location() {
        try {
            ResultSet set = locationData.getLocation();
            set.last();
            set.beforeFirst();
            while (set.next()) {
                String block_no = set.getString("location_name");
                location_select.addItem(block_no);
            }
            set.close();
            set = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Block Loading not complete ");
        }
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"TP", "Branch", "Location","Status","suctomer mobile id"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {

//                if (y == 7 || y == 8) {
                return false;
//                } else {
//                return true;
//                }

            }
        };

        tblGrid.setModel(model);
        tblGrid.getTableHeader().setPreferredSize(new Dimension(tblGrid.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = tblGrid.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
//        tblGrid.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
//        tblGrid.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
//        tblGrid.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);

        TableColumn coloumn4 = tblGrid.getColumnModel().getColumn(4);
        coloumn4.setMinWidth(0);
        coloumn4.setPreferredWidth(0);
        coloumn4.setMaxWidth(0);

        tblGrid.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        branch_save_btn = new javax.swing.JButton();
        branch_select = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        location_select = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        customer_tp_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrid = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Filter");

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Customer Data Filter");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 30));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel2.setText("Branch");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 100, 20));

        branch_save_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        branch_save_btn.setText("Search");
        branch_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(branch_save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 150, 25));

        branch_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(branch_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 240, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel4.setText("Location");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 100, 20));

        location_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        location_select.setToolTipText("");
        jPanel1.add(location_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 240, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel6.setText("Customer TP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 20));

        customer_tp_txt.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jPanel1.add(customer_tp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, 25));

        tblGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TP", "Branch", "Location"
            }
        ));
        tblGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrid);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1240, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branch_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_save_btnActionPerformed
       search_data();


    }//GEN-LAST:event_branch_save_btnActionPerformed

    public void search_data(){
     ShowGrid();

       
        String customer_tp = customer_tp_txt.getText();
        String branch_name = branch_select.getSelectedItem().toString();
        String location_name = location_select.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tblGrid.getModel();

        try {
            ResultSet set = customerMobileData.searchCustomerMobile(customer_tp, branch_name, location_name);
            set.last();
            set.beforeFirst();
            int x = 1;
            while (set.next()) {
//                String catagary_name = set.getString("catagary_name");

                model.addRow(new Object[]{set.getString("customer_mobile"), set.getString("branch_name"), set.getString("location_name"), set.getBoolean("status")?"Active":"Deactive"});
            }
            set.close();
            set = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mobile Data Loading not complete " + e);
        }
    }
    private void tblGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGridMouseClicked
        if (evt.getClickCount() == 2) {
            System.out.println("popup page came  >>>>>");
            CustomerDataUpdate MAS = new CustomerDataUpdate(null, true, 1, tblGrid.getValueAt(tblGrid.getSelectedRow(), 7).toString().trim()) {
                @Override
                public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {

                }
            };
            MAS.setVisible(true);
            MAS = null;
search_data();
        }
    }//GEN-LAST:event_tblGridMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton branch_save_btn;
    private javax.swing.JComboBox<String> branch_select;
    private javax.swing.JTextField customer_tp_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> location_select;
    private javax.swing.JTable tblGrid;
    // End of variables declaration//GEN-END:variables
}
